# MirageChatParser - Chat Strings Configuration

[General]
True = "Yes"
False = "No"

[Hoverable]
# Another suggestion "☆ "
ShinyIcon = "★ "

[Label]
# Another suggestion, "Species (Form): "
Species = "Species: "
# Another suggestion, "Level (EXP/EXP Needed): "
Level = "Level: "
Type = "Type: "
Types = "Types: "
Ability = "Ability: "
Nature = "Nature: "
NatureMinted = "Nature (Mint): "
IVs = "IVs: "
IVsHyperTrained = "IVs (Hyper Trained): "
EVs = "EVs: "
Moves = "Moves: "
Gender = "Gender: "
# Another suggestion, "Happiness: "
Friendship = "Friendship: "
HeldItem = "Held Item: "
CaughtBall = "Caught Ball: "
Size = "Size: "
EggGroups = "Egg Groups: "
Neutered = "Neutered: "
# Other suggestions, "OT: " and "Original Trainer (OT): "
OriginalTrainer = "Original Trainer: "

[Stat]
Health = "HP"
Attack = "Atk"
Defense = "Def"
SpecialAttack = "SpA"
SpecialDefense = "SpD"
Speed = "Spe"

[Value]
# Another suggestion, "Hidden Ability"
HiddenAbility = "HA"
TypeSeparator = "/"
# Other suggestions, "↑" and "⇧"
StatIncrease = "+"
# Other suggestions, "↓" and "⇩"
StatDecrease = "-"
# Another suggestion, " - "
MoveSeparator = ", "
MaleIcon = "♂"
FemaleIcon = "♀"
GenderlessIcon = "⚲"
EmptyHeldItem = "None"
EggGroupsSeparator = ", "
ClosedSheet = "Hidden"
UnknownPlayer = "Unknown Player"

[GUI]
PartyCheckTitle = "Party Check"
PartyCheckShoutTypeTitle = "Shout Type"
PartyCheckShoutVisibilityTitle = "Shout Visibility"
PartyCheckPokeShoutAllTitle = "PokeShoutAll"
GeneralShoutTypeName = "General Stats"
GeneralShoutTypeDescription = "General species/battle-specific information"
RideShoutTypeName = "Ride Stats"
RideShoutTypeDescription = "Mount-specific riding information"
RibbonsShoutTypeName = "Ribbons"
RibbonsShoutTypeDescription = "Pokémon ribbon-related information"
OpenShoutVisibilityName = "Open"
OpenShoutVisibilityDescription = "All information is displayed publicly"
ClosedShoutVisibilityName = "Closed"
ClosedShoutVisibilityDescription = "All battle-relevant information is hidden"
SelfShoutVisibilityName = "Self"
SelfShoutVisibilityDescription = "All information is only viewable by you"
PartyCheckFooter = "Click to cycle through the available options."
PartyCheckPartyShoutAllFooter = "Click to display all Pokémon in chat."
PartyCheckSplitter = " - "
